name: ci

on:
  push:
    branches: main
    # paths-ignore:
      # - '**/*.md'
      # - 'examples/**/*.html'

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: load cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: build packs
        run: |
          pnpm build:cache

      - name: run test
        run: |
          pnpm test

      - name: create versions or publish to npm registry
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changeset): release oplayer'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 已被墙
      # - name: build websites
      #   run: |
      #     pnpm i yarn -g
      #     cd website
      #     yarn
      #     yarn build:ghp

      # - name: deploy to github pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GIT_HUB_TOKEN }}
      #     publish_dir: ./website/build
      #     publish_branch: gh-pages
